services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/common/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #watchtower: updates all containers automatically
    #image: containrrr/watchtower
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
